---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-confd
description: confd docker image
tags:
  - docker
  - confd
github:
  has_issues: true
  has_projects: false
  has_wiki: false
